---
- hosts: web
  name: configuration play
  user: ubuntu

  # https://gist.github.com/gwillem/4ba393dceb55e5ae276a87300f6b8e6f#gistcomment-1914049
  gather_facts: false
  pre_tasks:
    - name: Install python for Ansible
      become: true
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: false
    - setup: # aka gather_facts

  tasks:

    - name: Install nginx
      become: true
      apt:
        name: nginx
        update_cache: true
